### PR TITLE
fix(util): exportText treat text as template string

### LINKED ISSUE #117: Proper escaping for strings
If snapshotted text has characters like ` or `${` it will result in an error. They should be escaped before save.

### PR DESCRIPTION
**Pull request by azu**
escape text by jsesc.
`jsesc` support `quote: "backtick"`.

fix #117

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -69,8 +69,14 @@ function exportText (name, value) {
     throw new Error(message)
   }
   la(is.unemptyString(value), 'expected string value', value)
-  const withNewLines = '\n' + value + '\n'
-  return `exports['${name}'] = \`${withNewLines}\`\n`
+  // jsesc replace "\n" with "\\n"
+  // https://github.com/mathiasbynens/jsesc/issues/20
+  const serialized = value.split('\n').map(line => {
```
Comment (azu) [inline src/utils.js]: jsesc does replace `\\n` with `\n`.

- https://github.com/mathiasbynens/jsesc/issues/20

File: src/utils-spec.js [hunk 2]
```diff
@@ -77,6 +77,26 @@ describe('exportText', () => {
...
+  it('does escape backtick on the text', () => {
+    const formatted = exportText('name', '`code`')
+    const expected = "exports['name'] = `\n\\`code\\`\n`\n"
+    la(formatted === expected, 'expected\n' + expected + '\ngot\n' + formatted)
+  })
+
+  it('does escape template variable on the text', () => {
+    /* eslint-disable no-template-curly-in-string */
+    const formatted = exportText('name', '`${1}`')
+    const expected = "exports['name'] = `\n\\`\\${1}\\`\n`\n"
```
Comment (azu) [inline src/utils-spec.js]: I also test following code is work.

	var exports = {};
    eval("exports['name'] = `\n\\`\\${1}\\`\n`\n")

**Comment by mike-north** [comment]
This PR looks good, it would be nice to see it merged, so I can strip out my workarounds.
